services:
  app:
    container_name: mujibai-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    container_name: mujibai-fe-nginx
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

networks:
  default:
    name: mujibai-net
