import type { SeoRoute } from './types';

export const SITE_NAME = 'mujibai';
export const SITE_CREATOR = 'mujibai';
export const SITE_PUBLISHER = 'mujibai';
export const DEFAULT_LOCALE = 'ar_SA';
export const DEFAULT_OG_IMAGE = '/loader-logo.svg';
export const SITE_EMAIL = 'tech@mujibai.net';

export const PUBLIC_SEO_ROUTES = [
  {
    key: 'home',
    path: '/',
    label: 'Home',
    title: 'mujibai - AI customer service agents for phone & web',
    description:
      'mujibai gives your business an AI customer service agent that answers phone calls and chats with website visitors, with easy landing page integration and no-code setup.',
    keywords: [
      'AI customer service',
      'AI phone agent',
      'AI call answering',
      'AI receptionist',
      'landing page AI chat integration',
      'mujibai',
    ],
    category: 'SoftwareApplication',
    priority: 1,
    changeFrequency: 'weekly',
    lastModified: '2026-06-27',
  },
  {
    key: 'helpCenter',
    path: '/help-center',
    label: 'Help Center',
    title: 'Help Center - mujibai',
    description:
      'Find guides and tutorials for setting up your AI customer service agent, connecting a phone number, and embedding mujibai on your landing page.',
    keywords: [
      'mujibai help center',
      'AI customer service support',
      'phone number setup guide',
      'landing page integration guide',
      'mujibai tutorials',
    ],
    category: 'Support',
    priority: 0.7,
    changeFrequency: 'weekly',
    lastModified: '2026-06-27',
  },
  {
    key: 'contactUs',
    path: '/contact',
    label: 'Contact',
    title: 'Contact us - mujibai',
    description:
      'Contact the mujibai team for sales, support, onboarding, and partnership questions about AI customer service.',
    keywords: [
      'contact mujibai',
      'mujibai sales',
      'mujibai support',
      'AI customer service software support',
      'business phone AI setup',
    ],
    category: 'Contact',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-06-27',
  },
  {
    key: 'privacyPolicy',
    path: '/privacy',
    label: 'Privacy Policy',
    title: 'Privacy Policy - mujibai',
    description:
      'How mujibai collects, uses, and protects personal and call/chat data across the product and website.',
    keywords: [
      'mujibai privacy policy',
      'data protection',
      'personal data',
      'call recording privacy',
      'AI customer service privacy',
    ],
    category: 'Legal',
    priority: 0.4,
    changeFrequency: 'yearly',
    lastModified: '2026-04-26',
  },
  {
    key: 'termsOfService',
    path: '/terms',
    label: 'Terms of Service',
    title: 'Terms of Service - mujibai',
    description:
      'Terms for using mujibai, including accounts, phone number provisioning, acceptable use, subscriptions, and liability.',
    keywords: [
      'mujibai terms',
      'terms of service',
      'SaaS terms',
      'subscription terms',
      'acceptable use',
    ],
    category: 'Legal',
    priority: 0.4,
    changeFrequency: 'yearly',
    lastModified: '2026-04-26',
  },
  {
    key: 'refundPolicy',
    path: '/refund-policy',
    label: 'Refund Policy',
    title: 'Refund Policy - mujibai',
    description:
      "mujibai's refund policy, including eligibility, non-refundable cases, duplicate charges, and how refund requests are reviewed.",
    keywords: [
      'mujibai refund policy',
      'refund eligibility',
      'SaaS refund policy',
      'subscription refunds',
      'billing support',
    ],
    category: 'Legal',
    priority: 0.4,
    changeFrequency: 'yearly',
    lastModified: '2026-07-01',
  },
  {
    key: 'cancellationPolicy',
    path: '/cancellation-policy',
    label: 'Cancellation Policy',
    title: 'Cancellation Policy - mujibai',
    description:
      "mujibai's cancellation policy, including subscription cancellation, access after cancellation, automatic renewal, and data retention.",
    keywords: [
      'mujibai cancellation policy',
      'cancel subscription',
      'SaaS cancellation policy',
      'automatic renewal',
      'data retention',
    ],
    category: 'Legal',
    priority: 0.4,
    changeFrequency: 'yearly',
    lastModified: '2026-07-01',
  },
  {
    key: 'aiVoiceAgent',
    path: '/ai-voice-agent',
    label: 'AI Voice Agent',
    title: 'AI Voice Agent - mujibai',
    description:
      'mujibai is an AI voice agent that answers business phone calls, books appointments, and creates tickets around the clock.',
    keywords: ['AI voice agent', 'AI phone agent', 'mujibai'],
    category: 'SoftwareApplication',
    priority: 0.9,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'aiCallCenter',
    path: '/ai-call-center',
    label: 'AI Call Center',
    title: 'AI Call Center - mujibai',
    description:
      'Run an AI-powered call center with mujibai: automated call answering, routing, and analytics for growing businesses.',
    keywords: ['AI call center', 'automated call center', 'mujibai'],
    category: 'SoftwareApplication',
    priority: 0.9,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'arabicAiReceptionist',
    path: '/arabic-ai-receptionist',
    label: 'Arabic AI Receptionist',
    title: 'Arabic AI Receptionist - mujibai',
    description:
      'A native-sounding Arabic AI receptionist that answers calls, understands local dialects, and handles requests for your business.',
    keywords: ['Arabic AI receptionist', 'Arabic voice agent', 'mujibai'],
    category: 'SoftwareApplication',
    priority: 0.9,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'automatedCustomerService',
    path: '/automated-customer-service',
    label: 'Automated Customer Service',
    title: 'Automated Customer Service - mujibai',
    description:
      'Automate customer service across phone and chat with mujibai, an AI agent that resolves requests without adding headcount.',
    keywords: ['automated customer service', 'AI customer service', 'mujibai'],
    category: 'SoftwareApplication',
    priority: 0.8,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'afterHoursCallAnswering',
    path: '/after-hours-call-answering',
    label: 'After-Hours Call Answering',
    title: 'After-Hours Call Answering - mujibai',
    description:
      'Never miss a call outside business hours. mujibai answers, triages, and books appointments after hours and on weekends.',
    keywords: ['after hours call answering', 'AI answering service', 'mujibai'],
    category: 'SoftwareApplication',
    priority: 0.8,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'pricing',
    path: '/pricing',
    label: 'Pricing',
    title: 'Pricing - mujibai',
    description:
      'mujibai pricing plans for AI customer service agents, phone number provisioning, and add-on usage.',
    keywords: ['mujibai pricing', 'AI agent pricing'],
    category: 'Pricing',
    priority: 0.8,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'demo',
    path: '/demo',
    label: 'Demo',
    title: 'Book a Demo - mujibai',
    description:
      'See mujibai in action. Book a live demo of the AI customer service agent for your business.',
    keywords: ['mujibai demo', 'book a demo'],
    category: 'Marketing',
    priority: 0.7,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'about',
    path: '/about',
    label: 'About',
    title: 'About mujibai',
    description:
      'Learn about mujibai and the team building AI customer service agents.',
    keywords: ['about mujibai', 'mujibai team'],
    category: 'Company',
    priority: 0.5,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'featuresIndex',
    path: '/features',
    label: 'Features',
    title: 'Features - mujibai',
    description:
      'Explore mujibai features: call answering, appointment booking, ticket creation, and more.',
    keywords: ['mujibai features'],
    category: 'SoftwareApplication',
    priority: 0.7,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'featureCallAnswering',
    path: '/features/call-answering',
    label: 'Call Answering',
    title: 'Call Answering - mujibai Features',
    description:
      'mujibai answers every inbound call with a natural-sounding AI voice agent.',
    keywords: ['AI call answering'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'featureAppointmentBooking',
    path: '/features/appointment-booking',
    label: 'Appointment Booking',
    title: 'Appointment Booking - mujibai Features',
    description:
      'Let mujibai book, reschedule, and confirm appointments directly on the call.',
    keywords: ['AI appointment booking'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'featureTicketCreation',
    path: '/features/ticket-creation',
    label: 'Ticket Creation',
    title: 'Ticket Creation - mujibai Features',
    description:
      'mujibai automatically creates and routes support tickets from every call.',
    keywords: ['AI ticket creation'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'featureKnowledgeBase',
    path: '/features/knowledge-base',
    label: 'Knowledge Base',
    title: 'Knowledge Base - mujibai Features',
    description:
      'Connect a knowledge base so mujibai answers questions with accurate, up-to-date information.',
    keywords: ['AI knowledge base'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'featureCallAnalytics',
    path: '/features/call-analytics',
    label: 'Call Analytics',
    title: 'Call Analytics - mujibai Features',
    description:
      'Understand call volume, outcomes, and trends with mujibai call analytics.',
    keywords: ['AI call analytics'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'featureCallRecording',
    path: '/features/call-recording',
    label: 'Call Recording',
    title: 'Call Recording - mujibai Features',
    description:
      'Every mujibai call is recorded and transcribed for quality and compliance.',
    keywords: ['AI call recording'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'featureIntegrations',
    path: '/features/integrations',
    label: 'Integrations',
    title: 'Integrations - mujibai Features',
    description: 'Connect mujibai to your CRM, helpdesk, and business systems.',
    keywords: ['mujibai integrations'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'featureArabicDialects',
    path: '/features/arabic-dialects',
    label: 'Arabic Dialects',
    title: 'Arabic Dialects - mujibai Features',
    description:
      'mujibai understands and speaks multiple Arabic dialects naturally.',
    keywords: ['Arabic dialects AI'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'industriesIndex',
    path: '/industries',
    label: 'Industries',
    title: 'Industries - mujibai',
    description:
      'See how mujibai helps clinics, real estate, restaurants, ecommerce, hotels, and maintenance companies.',
    keywords: ['mujibai industries'],
    category: 'SoftwareApplication',
    priority: 0.7,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'industryClinics',
    path: '/industries/clinics',
    label: 'Clinics',
    title: 'AI Agent for Clinics - mujibai',
    description:
      'mujibai answers patient calls, books appointments, and handles clinic front-desk requests.',
    keywords: ['AI agent for clinics'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'industryRealEstate',
    path: '/industries/real-estate',
    label: 'Real Estate',
    title: 'AI Agent for Real Estate - mujibai',
    description:
      'mujibai qualifies leads, books viewings, and answers property questions for real estate teams.',
    keywords: ['AI agent for real estate'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'industryRestaurants',
    path: '/industries/restaurants',
    label: 'Restaurants',
    title: 'AI Agent for Restaurants - mujibai',
    description:
      'mujibai takes reservations and answers common questions for restaurants.',
    keywords: ['AI agent for restaurants'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'industryEcommerce',
    path: '/industries/ecommerce',
    label: 'Ecommerce',
    title: 'AI Agent for Ecommerce - mujibai',
    description:
      'mujibai handles order status, returns, and support calls for ecommerce businesses.',
    keywords: ['AI agent for ecommerce'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'industryHotels',
    path: '/industries/hotels',
    label: 'Hotels',
    title: 'AI Agent for Hotels - mujibai',
    description:
      'mujibai answers reservation and guest-service calls for hotels around the clock.',
    keywords: ['AI agent for hotels'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
  {
    key: 'industryMaintenanceCompanies',
    path: '/industries/maintenance-companies',
    label: 'Maintenance Companies',
    title: 'AI Agent for Maintenance Companies - mujibai',
    description:
      'mujibai schedules service calls and creates work tickets for maintenance companies.',
    keywords: ['AI agent for maintenance companies'],
    category: 'SoftwareApplication',
    priority: 0.6,
    changeFrequency: 'monthly',
    lastModified: '2026-07-14',
  },
] as const satisfies readonly SeoRoute[];

export const DISALLOWED_ROUTES = ['/auth', '/dashboard'] as const;
